version: "3.7"
services:
  app:
    build: .
    ports:
     - 3001:3001
    env_file: .env
    depends_on: 
     - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
     - 5432:5432
    volumes:
      - db-data:/var/lib/postgres/data
volumes:
  db-data: